/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExportRouteImport } from './routes/export'
import { Route as EpicsRouteImport } from './routes/epics'
import { Route as IndexRouteImport } from './routes/index'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicsRoute = EpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epics': typeof EpicsRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/projects': typeof ProjectsRoute
  '/requirements': typeof RequirementsRoute
  '/stories': typeof StoriesRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epics': typeof EpicsRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/projects': typeof ProjectsRoute
  '/requirements': typeof RequirementsRoute
  '/stories': typeof StoriesRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epics': typeof EpicsRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/projects': typeof ProjectsRoute
  '/requirements': typeof RequirementsRoute
  '/stories': typeof StoriesRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epics'
    | '/export'
    | '/history'
    | '/projects'
    | '/requirements'
    | '/stories'
    | '/upload'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epics'
    | '/export'
    | '/history'
    | '/projects'
    | '/requirements'
    | '/stories'
    | '/upload'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/epics'
    | '/export'
    | '/history'
    | '/projects'
    | '/requirements'
    | '/stories'
    | '/upload'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpicsRoute: typeof EpicsRoute
  ExportRoute: typeof ExportRoute
  HistoryRoute: typeof HistoryRoute
  ProjectsRoute: typeof ProjectsRoute
  RequirementsRoute: typeof RequirementsRoute
  StoriesRoute: typeof StoriesRoute
  UploadRoute: typeof UploadRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epics': {
      id: '/epics'
      path: '/epics'
      fullPath: '/epics'
      preLoaderRoute: typeof EpicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpicsRoute: EpicsRoute,
  ExportRoute: ExportRoute,
  HistoryRoute: HistoryRoute,
  ProjectsRoute: ProjectsRoute,
  RequirementsRoute: RequirementsRoute,
  StoriesRoute: StoriesRoute,
  UploadRoute: UploadRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
